--- # PLAYBOOK COPY EXAMPLE
- hosts: apacheweb
  user: testuser
  become: yes
  gather_facts: no
  tasks:
  - name: Copy from the files dir test files
    action: copy src=files/test1.txt dest=/home/testuser/test1.txt
