--- # VARIABLES AT A COMMAND LINE PASSING EXAMPLE
- hosts: '{{ hosts }}'
  user: '{{ user }}'
  become: yes
  gather_facts: no
  tasks: 
  - name: Install some software
    yum: pkg={{ pkg }} state=latest
