--- # service module example
- hosts: apacheweb
  user: testuser
  become: yes
  gather_facts: yes
  tasks:
  - name: Install Web Server
    action: yum name=httpd state=installed
  - name: Start Web Server
    service: name=httpd state=started
  - name: Enable HTTPD after reboot
    service: name=httpd enabled=yes
