--- # START AT PLAYBOOK EXAMPLE
- hosts: apacheweb
  user: testuser
  become: yes
  gather_facts: no
  tasks:
    - name: Install telnet
      yum: pkg=telnet state=latest
    - name: Install lynx
      yum: pkg=lynx state=latest
    - name: List Home
      command: ls -al /home/testuser
      register: result
    - debug: var=result

