--- # BITCHES LOVE CONDITIONALS TEST
- hosts: aptserver 
  become: yes
  gather_facts: yes
  user: testuser
  vars:
    playbook_type: conditionalexample
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  tasks:
    - name: Install Apache Appropriate to the Dist Type Debian
      command: apt-get -y install apache2
      when: ansible_os_family == "Debian"
    - name: Install Apache Appropriate to the Dist Type RH/CentOS
      command: yum -y install httpd
      when: ansible_os_family == "RedHat"
